### PR TITLE
Add Eval of Performance

### PR DESCRIPTION
**Pull request by NMerz**
Still in progress. Will continue to update.

### CODE REVIEW

**Comment by NMerz** [comment]
@pandeyshubham25 The first commit here has some build configs that need to be preserved in however we ultimately decide to build since openMP does not work right out of the box with Apple's clang distribution.

**Comment by NMerz** [comment]
Basic timing graph is done.
To run using test mode:
```
make test
./eval
```

I'm not positive the popen works on Windows (or were you planning on running on Linux?). For Windows, I'm thinking I'll need to add an OS define and use _popen as needed.


@pandeyshubham25 With working on measuring correctness, did you have any idea on how you wanted to output the results of Pagerank?

**Comment by NMerz** [comment]
From a Mac standpoint of very basic graphs for timing, this should be good to go.

**Comment by pandeyshubham25** [comment]
Regarding popen, I am working on this project using my Linux OS so should be fine.
As for correctness, I was thinking just the sorted order of IDs (newline separated or rather space separated) and not worrying about the weights that decide their rank. What are your thoughts on this ?

**Pull request merged**
